spring.application.name=transit-service
server.port=8083

AUTH_ISSUER_URI=${AUTH_ISSUER_URI:http://localhost:8081/realms/kulturnatten-dev}
AUTH_JWK_SET_URI=${AUTH_JWK_SET_URI:http://localhost:8081/realms/kulturnatten-dev/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health
