spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: jdbc:sqlite::resource:database/events.db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}

