spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kulturnatten
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never